### ISSUE TITLE
Carrito y footer

### ISSUE THREAD

**Issue by pmarino2013** [matiasBRH/electro-rolling-web#20]
Se cargan los productos en el carrito pero no se actualiza en la barra de menú el total. También se observa que cuando una página tiene poco contenido en el cuerpo el footer no queda fijado abajo sino que sube.

![image](https://user-images.githubusercontent.com/35234004/193282571-c0dc3409-463c-4dca-9775-d8fe74546d07.png)

**Comment by matiasBRH** [comment]
Solucionado en PR #21.
